Updated the readme about Camel LS integration with Vim using Neoclide
camel-tooling/coc-camel pull request #1
Opened 2022-06-26 17:15 UTC by Navyashree0923

2022-06-27 06:48 UTC, apupier requested changes

2022-06-27 06:48 UTC, apupier commented on README.md
> +Add these plugins in your `.vimrc` or `init.vim`
```suggestion
Add this plugin in your `.vimrc` or `init.vim`
```

2022-06-27 06:48 UTC, apupier commented on README.md
> +### Configuration is required to make coc.nvim easier to work with. This is done as much as possible to avoid conflict with other plugins.
I guess this is not required. if you want you might provide a link to the documentation of coc.nvim about this subject

2022-06-27 08:30 UTC, apupier approved these changes

2022-07-06 13:37 UTC, Navyashree0923 commented
Closing this PR w.r.t #2

2022-07-06 13:37 UTC, closed without merging