Adding the coc extensions for Apache Camel
camel-tooling/coc-camel pull request #2
Opened 2022-07-05 11:42 UTC by Navyashree0923

2022-07-05 12:44 UTC, apupier requested changes

2022-07-05 12:44 UTC, apupier commented on src/index.ts
> +        // command: '/usr/bin/java -jar'.concat(' ').concat(jarPath).toString() // run camells
commented line can be removed

2022-07-05 12:44 UTC, apupier commented on src/index.ts
> +        documentSelector: ['java', 'xml'] // run camells on java files
not working for yaml files?

2022-07-05 12:44 UTC, apupier commented on src/jarDownload.ts
> +// console.log("Complete url:", url)
commented code to remove

2022-07-05 12:44 UTC, apupier commented on src/jarDownload.ts
> +    // console.log("camellsJar:", jar_Url + jar_Version + '/' + jar_Name + jar_Version + '.jar')
commented code to remove

2022-07-05 12:44 UTC, apupier commented on src/jarDownload.ts
> +                 // console.log("Download Completed")
commened code to remove

2022-07-05 12:44 UTC, apupier commented on src/index.ts
> +    // console.log("Couldn't find Jar File, So downloading the Camel LS Jar")
commented code to remove

2022-07-05 12:44 UTC, apupier commented on src/index.ts
> +    suffix: '.jar'
wrong indentation. This should have one more level of indentation.

2022-07-05 12:44 UTC, apupier commented on src/index.ts
> +      if (!isEnable) {
wrong indentation

2022-07-05 12:44 UTC, apupier commented on package.json
> +  "description": "",
would be nice to add a description

2022-07-05 12:44 UTC, apupier commented on package.json
> +  ],
other Keyword suggestions:
- Apache Camel
- vim

2022-07-05 12:44 UTC, apupier commented on README.md
> +MIT
License is Apache

2022-07-05 12:44 UTC, apupier commented on README.md
> +`:CocList demo_list`
What is the this command doing?

2022-07-05 12:44 UTC, apupier commented on src/index.ts
> +                             true
wrong indentation on some of the lines

2022-07-05 12:44 UTC, apupier commented on README.md
> +
Would be nice to include a description of the covered features in the readme. Providing animated image would be nice too.
it is also possible to handle it in another iteration (and so create an issue for it, then provide a different Pull Request)

2022-07-06 04:56 UTC, Navyashree0923 commented
Thank you for the feedback. I have updated the PR with the modifications

2022-07-06 06:30 UTC, apupier commented
it remains two of my comments not adressed:
- https://github.com/camel-tooling/coc-camel/pull/2#discussion_r913749237
- https://github.com/camel-tooling/coc-camel/pull/2#discussion_r913749901

2022-07-06 06:37 UTC, apupier requested changes
I'm unable to build locally.
What are the steps to do the build? Would be nice to indicate them in a Contributing.md file.

Edit: got a build with the following steps:
```
npm install esbuild
yarn
```
Is it the right ones?

2022-07-06 13:28 UTC, Navyashree0923 commented
> I'm unable to build locally. What are the steps to do the build? Would be nice to indicate them in a Contributing.md file.
> 
> Edit: got a build with the following steps:
> 
> ```
> npm install esbuild
> yarn
> ```
> 
> Is it the right ones?

Yeah these are correct. I have added a new session in the readme on how to contribute instead of creating a new contribute.md file.
Thanks for the feedback

2022-07-06 13:30 UTC, Navyashree0923 commented
I have also added a `.gitignore` to avoid tracking of files like `node_modules`, `lib`, etc

2022-07-06 13:39 UTC, apupier approved these changes
Sounds great!

2022-07-08 07:33 UTC, merged